### ISSUE TITLE
Unable to compile class for JSP after including the metro.js file instead of using jsp

### ISSUE THREAD

**Issue by jbcostan** [olton/metroui#1829]
**Describe the bug**
other libraries that I include works fine and even the metro4 css is fine, but the metro4.js creates the unable to compile.

**My JSP File**
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1" maximum-scale=1.0, user-scalable=no" >
    <meta name="keyword" content="Romenext"/>
    <link rel="icon" href="/webguiportal/webgui/src/Grass_5.ico?" type="image/x-icon" />

                
    <style type="text/css">
        <%@include file="/assets/css/metro.min.css" %>
    </style>

    <script type="text/javascript">
        <%@include file="/assets/js/libs/jquery/3.6.0/jquery-3.6.0.slim.min.js" %> 
        <%@include file="/assets/js/libs/metro4/metro.js" %>
    </script> 

    
    <style>
        body {
            overflow: hidden;
        }

        #myForm {
            height: 85vh;
        }

        .img-text {
            position: absolute;
            top: 36%;
            left: 80px;
            right: 80px;
            background: rgba(255, 255, 255, 0.6);
        }
    </style>
</head>

** Error**

> org.apache.jasper.JasperException: JBWEB004062: Unable to compile class for JSP: 
> 
> JBWEB004060: An error occurred at line: 24568 in the jsp file: /assets/js/libs/metro4/metro.js
> String literal is not properly closed by a double-quote
> 24565:     var ListDefaultConfig = {
> 24566:         locale: METRO_LOCALE,
> 24567:         listDeferred: 0,
> 24568:         templateBeginToken: "<%",
> 24569:         templateEndToken: "%>",
> 24570:         paginationDistance: 5,
> 24571:         paginationShortMode: true,
> 
> 
> Stacktrace:
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:95)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:198)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:455)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.Compiler.compile(Compiler.java:359)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.Compiler.compile(Compiler.java:334)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.compiler.Compiler.compile(Compiler.java:321)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:652)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:358)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:403)
> 	at io.undertow.jsp@2.0.9.Final//org.apache.jasper.servlet.JspServlet.service(JspServlet.java:347)

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Metro Version [e.g. 4.5.0]

**Comment by olton** [comment]
This is a not library problem, check your definitions
